data = ["nop","lxib,d16","staxb","inxb","inrb","dcrb","mvib,d8","rlc","dadb","ldaxb","dcxb","inrc","dcrc","mvic,d8","rrc","lxid,d16","staxd","inxd","inrd","dcrd","mvid,d8","ral","dadd","ldaxd","dcxd","inre","dcre","mvie,d8","rar","rim","lxih,d16","shldadr","inxh","inrh","dcrh","mvih,d8","daa","dadh","lhldadr","dcxh","inrl","dcrl","mvil,d8","cma","sim","lxisp,d16","staadr","inxsp","inrm","dcrm","mvim,d8","stc","dadsp","ldaadr","dcxsp","inra","dcra","mvia,d8","cmc","movb,b","movb,c","movb,d","movb,e","movb,h","movb,l","movb,m","movb,a","movc,b","movc,c","movc,d","movc,e","movc,h","movc,l","movc,m","movc,a","movd,b","movd,c","movd,d","movd,e","movd,h","movd,l","movd,m","movd,a","move,b","move,c","move,d","move,e","move,h","move,l","move,m","move,a","movh,b","movh,c","movh,d","movh,e","movh,h","movh,l","movh,m","movh,a","movl,b","movl,c","movl,d","movl,e","movl,h","movl,l","movl,m","movl,a","movm,b","movm,c","movm,d","movm,e","movm,h","movm,l","hlt","movm,a","mova,b","mova,c","mova,d","mova,e","mova,h","mova,l","mova,m","mova,a","addb","addc","addd","adde","addh","addl","addm","adda","adcb","adcc","adcd","adce","adch","adcl","adcm","adca","subb","subc","subd","sube","subh","subl","subm","suba","sbbb","sbbc","sbbd","sbbe","sbbh","sbbl","sbbm","sbba","anab","anac","anad","anae","anah","anal","anam","anaa","xrab","xrac","xrad","xrae","xrah","xral","xram","xraa","orab","orac","orad","orae","orah","oral","oram","oraa","cmpb","cmpc","cmpd","cmpe","cmph","cmpl","cmpm","cmpa","rnz","popb","jnzadr","jmpadr","cnzadr","pushb","adid8","rst0","rz","ret","jzadr","czadr","calladr","acid8","rst1","rnc","popd","jncadr","outd8","cncadr","pushd","suid8","rst2","rc","jcadr","ind8","ccadr","sbid8","rst3","rpo","poph","jpoadr","xthl","cpoadr","pushh","anid8","rst4","rpe","pchl","jpeadr","xchg","cpeadr","xrid8","rst5","rp","poppsw","jpadr","di","cpadr","pushpsw","pusha","orid8","rst6","rm","sphl","jmadr","ei","cmadr","cpid8","rst7"]
data_dict = set()

for d in data:
    if len(d) > 3:
        data_dict.add(d[3])

print(data_dict)



another_data = ["nop","lxi","stax","inx","inr","dcr","mvi","rlc","dad","ldax","dcx","inr","dcr","mvi","rrc","lxi","stax","inx","inr","dcr","mvi","ral","dad","ldax","dcx","inr","dcr","mvi","rar","rim","lxi","shld","inx","inr","dcr","mvi","daa","dad","lhld","dcx","inr","dcr","mvi","cma","sim","lxi","sta","inx","inr","dcr","mvi","stc","dad","lda","dcx","inr","dcr","mvi","cmc","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","mov","hlt","mov","mov","mov","mov","mov","mov","mov","mov","mov","add","add","add","add","add","add","add","add","adc","adc","adc","adc","adc","adc","adc","adc","sub","sub","sub","sub","sub","sub","sub","sub","sbb","sbb","sbb","sbb","sbb","sbb","sbb","sbb","ana","ana","ana","ana","ana","ana","ana","ana","xra","xra","xra","xra","xra","xra","xra","xra","ora","ora","ora","ora","ora","ora","ora","ora","cmp","cmp","cmp","cmp","cmp","cmp","cmp","cmp","rnz","pop","jnz","jmp","cnz","push","adi","rst","rz","ret","jz","cz","call","aci","rst","rnc","pop","jnc","out","cnc","push","sui","rst","rc","jc","in","cc","sbi","rst","rpo","pop","jpo","xthl","cpo","push","ani","rst","rpe","pchl","jpe","xchg","cpe","xri","rst","rp","pop","jp","di","cp","push","push","ori","rst","rm","sphl","jm","ei","cm","cpi","rst"]

for i in set(another_data):
    print("\"{}\" => <>".format(i))

