[package]
name = "lalrpop"
version = "0.1.0"
edition = "2021"

[build-dependencies] # <-- We added this and everything after!
lalrpop = "0.19.7"

[dependencies]
regex = "1"

[dependencies.lalrpop-util]
version = "0.19.7"

[dependencies.lalrpop]
version = "0.19.7"
features = ["lexer"]
